# Generated by Django 4.0.1 on 2022-01-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('random_number', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
